export default[
    {
        "id": 1,
        "name": "Team Building",
        "date": "17.01.2024 @ 9:00 am",
        "time": "9:00 am - 9:00 am",
        "venue": "Harward Education",
        "address": "Cambridge, MA 04245, USA",
        "details": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. ",
        "image": "../Images/EventsDataApi/event-single-1.jpg",
        "organization": "Qode Interactive",
        "phone": "+923169727859",
        "email": "adnan191022@gmail.com",
        "website": "https://youtube.com/@information3214"
    },
    {
        "id": 2,
        "name": "Networking Day",
        "date": "17.01.2024 @ 9:00 am",
        "time": "9:00 am - 9:00 am",
        "venue": "Harward Education",
        "address": "Cambridge, MA 04245, USA",
        "details": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. ",
        "image": "../Images/EventsDataApi/event-single-11.jpg",
        "organization": "Qode Interactive",
        "phone": "+923169727859",
        "email": "adnan191022@gmail.com",
        "website": "https://youtube.com/@information3214"
    },
    {
        "id": 3,
        "name": "Open Door Days",
        "date": "17.01.2024 @ 9:00 am",
        "time": "9:00 am - 9:00 am",
        "venue": "Harward Education",
        "address": "Cambridge, MA 04245, USA",
        "details": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. ",
        "image": "../Images/EventsDataApi/event-single-2.jpg",
        "organization": "Qode Interactive",
        "phone": "+923169727859",
        "email": "adnan191022@gmail.com",
        "website": "https://youtube.com/@information3214"
    },
    {
        "id": 4,
        "name": "Personal Tutoring",
        "date": "17.01.2024 @ 9:00 am",
        "time": "9:00 am - 9:00 am",
        "venue": "Harward Education",
        "address": "Cambridge, MA 04245, USA",
        "details": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. ",
        "image": "../Images/EventsDataApi/event-single-1.jpg",
        "organization": "Qode Interactive",
        "phone": "+923169727859",
        "email": "adnan191022@gmail.com",
        "website": "https://youtube.com/@information3214"
    },
    {
        "id": 5,
        "name": "Friendship Day",
        "date": "17.01.2024 @ 9:00 am",
        "time": "9:00 am - 9:00 am",
        "venue": "Harward Education",
        "address": "Cambridge, MA 04245, USA",
        "details": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. ",
        "image": "../Images/EventsDataApi/event-single-3.jpg",
        "organization": "Qode Interactive",
        "phone": "+923169727859",
        "email": "adnan191022@gmail.com",
        "website": "https://youtube.com/@information3214"
    },
    {
        "id": 6,
        "name": "Children Day",
        "date": "17.01.2024 @ 9:00 am",
        "time": "9:00 am - 9:00 am",
        "venue": "Harward Education",
        "address": "Cambridge, MA 04245, USA",
        "details": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. ",
        "image": "../Images/EventsDataApi/event-single-6.jpg",
        "organization": "Qode Interactive",
        "phone": "+923169727859",
        "email": "adnan191022@gmail.com",
        "website": "https://youtube.com/@information3214"
    },
    {
        "id": 7,
        "name": "Team Building",
        "date": "17.01.2024 @ 9:00 am",
        "time": "9:00 am - 9:00 am",
        "venue": "Harward Education",
        "address": "Cambridge, MA 04245, USA",
        "details": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. ",
        "image": "../Images/EventsDataApi/event-single-1.jpg",
        "organization": "Qode Interactive",
        "phone": "+923169727859",
        "email": "adnan191022@gmail.com",
        "website": "https://youtube.com/@information3214"
    },
    {
        "id": 8,
        "name": "Team Building",
        "date": "17.01.2024 @ 9:00 am",
        "time": "9:00 am - 9:00 am",
        "venue": "Harward Education",
        "address": "Cambridge, MA 04245, USA",
        "details": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. ",
        "image": "../Images/EventsDataApi/event-single-1.jpg",
        "organization": "Qode Interactive",
        "phone": "+923169727859",
        "email": "adnan191022@gmail.com",
        "website": "https://youtube.com/@information3214"
    },
    {
        "id": 9,
        "name": "Team Building",
        "date": "17.01.2024 @ 9:00 am",
        "time": "9:00 am - 9:00 am",
        "venue": "Harward Education",
        "address": "Cambridge, MA 04245, USA",
        "details": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. ",
        "image": "../Images/EventsDataApi/event-single-1.jpg",
        "organization": "Qode Interactive",
        "phone": "+923169727859",
        "email": "adnan191022@gmail.com",
        "website": "https://youtube.com/@information3214"
    },
    {
        "id": 10,
        "name": "Team Building",
        "date": "17.01.2024 @ 9:00 am",
        "date1":"17 Jan",
        "time": "9:00 am - 9:00 am",
        "venue": "Harward Education",
        "address": "Cambridge, MA 04245, USA",
        "details": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. ",
        "image": "../Images/EventsDataApi/event-single-1.jpg",
        "organization": "Qode Interactive",
        "phone": "+923169727859",
        "email": "adnan191022@gmail.com",
        "website": "https://youtube.com/@information3214"
    },
]